kind: Service
apiVersion: v1
metadata:
  name: imisham-service
  labels:
    type: webapp
spec:
  selector:
    app: webservice
  ports: 
    - name: http
      port: 8008
      targetPort: 8000
      protocol: TCP
      nodePort: 31201
  type: LoadBalancer

