kind: Deployment
apiVersion: apps/v1
metadata:
  name: imisham-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webservice
  template:
    metadata:
      name: imisham-webapp
      labels:
        app: webservice
    spec:
      containers:
        - name: webapp
          image: eyash27/imisham-pipeline:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

