kind: Service
apiVersion: v1
metadata:
  name: imisham-service
  labels:
    type: webapp
spec:
  selector:
    type: webapp
  ports: 
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 31200
  type: LoadBalancer

