# Generated by Django 4.0 on 2023-04-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamisham_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('choice_text', 'question')},
        ),
    ]
