# Generated by Django 4.2.2 on 2024-01-24 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iamisham_app', '0002_alter_choice_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ManyToManyField(related_name='choices', to='iamisham_app.question'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='iamisham_app.question'),
        ),
    ]
