# Generated by Django 4.2.2 on 2024-01-24 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iamisham_app', '0003_alter_choice_question_alter_testquestion_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iamisham_app.question'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='iamisham_app.test'),
        ),
    ]
