# Generated by Django 4.2.2 on 2024-01-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iamisham_app', '0004_alter_testquestion_question_alter_testquestion_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctchoice',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='iamisham_app.question'),
        ),
    ]
